# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

#BASE_PATH : http://blog.ankanbiswas.in/uno-dbyll
BASE_PATH : http://goileo.top

description : 来自安徽大别山贫困山区的孩子
title : Liu Pengfei
logo : /assets/images/avatar.jpg
#cover : /assets/images/background-cover.jpg


author:
  name: Liu Pengfei
  maxim: Stay hungry,Stay foolish
  role: Jekyll Theme
  bio: "Hi, 我是刘鹏飞"
  uno-dbyll: /assets/images/avatar.jpg

theme: jekyll-theme-cayman